# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregate_bins_cpp_sparse <- function(targ_bins, query_hits, subject_hits, signal_matrix, num_bins) {
    .Call(`_atacInferCnv_aggregate_bins_cpp_sparse`, targ_bins, query_hits, subject_hits, signal_matrix, num_bins)
}

